---
galaxy_info:
  role_name: vector_role
  author: RomanDiskTop
  description: Install and configure Vector on Debian/Ubuntu hosts
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble
  galaxy_tags:
    - vector
    - logging
    - observability

dependencies: []
