all:
  hosts:
    clickhouse:
      ansible_host: 51.250.106.181
    vector:
      ansible_host: 89.169.181.86
    lighthouse:
      ansible_host: 89.169.165.79

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: /root/.ssh/id_rsa
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
